stages:
  prepare:
    foreach: ${vpuids}
    do:
      cmd: >
        docker compose run --rm hydrofabric ./bash/prepare_reference_gpkg.sh
        ${item.id}
        /ngen-workflow/data/superconus/divides/vpuid_${item.id}.parquet
        /ngen-workflow/data/superconus/flowpaths/vpuid_${item.id}.parquet
        /ngen-workflow/data/superconus/hydrolocations/vpuid_${item.id}.parquet
        /ngen-workflow/data/superconus/network/vpuid_${item.id}.parquet
        /ngen-workflow/data/superconus/pois.parquet
      deps:
        - ../../ngen-workflow/bash/prepare_reference_gpkg.sh
        - ../../ngen-workflow/data/superconus/divides/vpuid_${item.id}.parquet
        - ../../ngen-workflow/data/superconus/flowpaths/vpuid_${item.id}.parquet
        - ../../ngen-workflow/data/superconus/hydrolocations/vpuid_${item.id}.parquet
        - ../../ngen-workflow/data/superconus/network/vpuid_${item.id}.parquet
        - ../../ngen-workflow/data/superconus/pois.parquet
      outs:
        - ../../ngen-workflow/data/prepared/${item.id}/reference_hydrofabric.gpkg
  refactor:
    foreach: ${vpuids}
    do:
      cmd: >
        docker compose run --rm hydrofabric ./bash/run-refactor.sh
        /ngen-workflow/data/NHDSnapshot/FAC/${item.prefix}a_fac.tif
        /ngen-workflow/data/NHDSnapshot/FDR/${item.prefix}a_fdr.tif
        /ngen-workflow/data/prepared/${item.id}/reference_hydrofabric.gpkg
        /ngen-workflow/data/refactored/${item.id}/refactored_reference_hydrofabric.gpkg
        ${refactor.split_flines_meters}
        ${refactor.collapse_flines_meters}
        ${refactor.collapse_flines_main_meters}
        ${refactor.simplify_tolerance_meters}
      params:
        - refactor.split_flines_meters
        - refactor.collapse_flines_meters
        - refactor.collapse_flines_main_meters
        - refactor.simplify_tolerance_meters
      deps:
        - ../../ngen-workflow/bash/run-refactor.sh
        - ../../ngen-workflow/R/refactor.Rmd
        - ../../ngen-workflow/data/prepared/${item.id}/reference_hydrofabric.gpkg
        - ../../ngen-workflow/data/NHDSnapshot/FAC/${item.prefix}a_fac.tif
        - ../../ngen-workflow/data/NHDSnapshot/FDR/${item.prefix}a_fdr.tif
      outs:
        - ../../ngen-workflow/data/refactored/${item.id}/refactored_reference_hydrofabric.gpkg
  aggregate:
    foreach: ${vpuids}
    do:
      cmd: >
        docker compose run --rm hydrofabric ./bash/run-aggregate.sh
        /ngen-workflow/data/refactored/${item.id}/refactored_reference_hydrofabric.gpkg
        /ngen-workflow/data/aggregated/${item.id}/aggregate_outlets.gpkg
        /ngen-workflow/data/aggregated/${item.id}/aggregate_distribution.gpkg
        ${aggregate.ideal_size_sqkm}
        ${aggregate.min_length_km}
        ${aggregate.min_area_sqkm}
      params:
        - aggregate.ideal_size_sqkm
        - aggregate.min_length_km
        - aggregate.min_area_sqkm
      deps:
        - ../../ngen-workflow/R/aggregate.Rmd
        - ../../ngen-workflow/data/refactored/${item.id}/refactored_reference_hydrofabric.gpkg
      outs:
        - ../../ngen-workflow/data/aggregated/${item.id}/aggregate_outlets.gpkg
        - ../../ngen-workflow/data/aggregated/${item.id}/aggregate_distribution.gpkg
  hfngen:
    foreach: ${vpuids}
    do:
      cmd: >
        docker compose run --rm hydrofabric ./bash/run-hfngen.sh
        /ngen-workflow/data/aggregated/${item.id}/aggregate_distribution.gpkg
        /ngen-workflow/data/refactored/${item.id}/refactored_reference_hydrofabric.gpkg
        /ngen-workflow/data/ngen/${item.id}/ngen_hydrofabric.gpkg
      deps:
        - ../../ngen-workflow/R/hfngen.Rmd
        - ../../ngen-workflow/data/aggregated/${item.id}/aggregate_distribution.gpkg
        - ../../ngen-workflow/data/refactored/${item.id}/refactored_reference_hydrofabric.gpkg
      outs:
        - ../../ngen-workflow/data/ngen/${item.id}/ngen_hydrofabric.gpkg
  minimal_attributes:
    foreach: ${vpuids}
    do:
      cmd: >
        docker compose run --rm hydrofabric ./bash/run-minimal-attributes.sh
        /ngen-workflow/data/ngen/${item.id}/ngen_hydrofabric.gpkg
        /ngen-workflow/data/superconus/gridded/ISLTYP.tif
        /ngen-workflow/data/superconus/gridded/IVGTYP.tif
        /ngen-workflow/data/superconus/derived/CONUS_imp_240.tif
        /ngen-workflow/data/superconus/tabular/nwm_gw_basins.parquet
        /ngen-workflow/data/superconus/tabular/riverml_channel_geometry_with_ahg.parquet
        /ngen-workflow/data/ngen/${item.id}/${minimal_attributes.output_geopackage_name}

      deps:
        - ../../ngen-workflow/R/minimal_attributes.Rmd
        - ../../ngen-workflow/data/ngen/${item.id}/ngen_hydrofabric.gpkg
        - ../../ngen-workflow/data/superconus/gridded/ISLTYP.tif
        - ../../ngen-workflow/data/superconus/gridded/IVGTYP.tif
        - ../../ngen-workflow/data/superconus/derived/CONUS_imp_240.tif
        - ../../ngen-workflow/data/superconus/tabular/nwm_gw_basins.parquet
        - ../../ngen-workflow/data/superconus/tabular/riverml_channel_geometry_with_ahg.parquet
      outs:
        - ../../ngen-workflow/data/ngen/${item.id}/${minimal_attributes.output_geopackage_name}
  reconcile:
    foreach: ${vpuids}
    do:
      cmd: >
        docker compose run --rm hydrofabric ./bash/run-reconcile.sh
        /ngen-workflow/data/ngen/${item.id}/${minimal_attributes.output_geopackage_name}
        ${item.id}
        /ngen-workflow/data/ngen/${item.id}/${reconcile.output_geopackage_name}
      deps:
        - ../../ngen-workflow/R/reconcile.Rmd
        - ../../ngen-workflow/data/ngen/${item.id}/${minimal_attributes.output_geopackage_name}
      outs:
        - ../../ngen-workflow/data/ngen/${item.id}/${reconcile.output_geopackage_name}
