vpuids:
  - id: "01"
    prefix: "01"
  - id: "02"
    prefix: "02"
  - id: "03N"
    prefix: "03"
  - id: "03S"
    prefix: "03"
  - id: "03W"
    prefix: "03"
  - id: "04"
    prefix: "04"
  - id: "05"
    prefix: "05"
  - id: "06"
    prefix: "06"
  - id: "07"
    prefix: "07"
  - id: "08"
    prefix: "08"
  - id: "09"
    prefix: "09"
  - id: "10L"
    prefix: "10"
  - id: "10U"
    prefix: "10"
  # - id: "11"
  #   prefix: "11" -   Error
  - id: "12"
    prefix: "12"
  - id: "13"
    prefix: "13"
  - id: "14"
    prefix: "14"
  - id: "15"
    prefix: "15"
  - id: "16"
    prefix: "16"
  - id: "17"
    prefix: "17"
  # - id: "18"
  #   prefix: "18" -   Error in `aggregate.data.frame()`:
#! no rows to aggregate
#Backtrace:
#     ▆
#  1. ├─hfrefactor::refactor(...)
#  2. │ └─hfrefactor:::.clean(...)
#  3. │   ├─sf::st_as_sf(...)
#  4. │   ├─data.table::rbindlist(...)
#  5. │   ├─base::merge(...)
#  6. │   ├─dplyr::mutate(...)
#  7. │   ├─data.table::as.data.table(...)
#  8. │   └─hydrofab::union_polygons(...)
#  9. │     └─... %>% select(!!ID)
# 10. ├─dplyr::select(., !!ID)
# 11. ├─sf::st_as_sf(.)
# 12. ├─stats::aggregate(., by = eval(ID))
# 13. └─terra::aggregate(., by = eval(ID))
# 14.   └─terra (local) .local(x, ...)
# 15.     └─terra:::aggregate_attributes(...)
# 16.       ├─stats::aggregate(...)
# 17.       ├─stats::aggregate(...)
# 18.       └─stats::aggregate.data.frame(...)
refactor:
  split_flines_meters: 10000
  collapse_flines_meters: 1000
  collapse_flines_main_meters: 1000
  simplify_tolerance_meters: 400
aggregate:
  ideal_size_sqkm: 25
  min_length_km: 1
  min_area_sqkm: 10