vpuids:
  - "01"
  - "02"
  # missing- "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  # missing- "09"
  # missing- "10"
  # erroring- "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"    
refactor:
  split_flines_meters: 10000
  collapse_flines_meters: 1000
  collapse_flines_main_meters: 1000
  simplify_tolerance_meters: 400
aggregate:
  ideal_size_sqkm: 25
  min_length_km: 1
  min_area_sqkm: 10