services:
  hydrofabric:
    user: "1000:1000"
    #image: joshcu/chdvc:latest # uncomment to use pre-built image from DockerHub
    build:
      context: ./ngen-workflow/
      dockerfile: Dockerfile
    volumes:
      - ./ngen-workflow:/ngen-workflow
    working_dir: /ngen-workflow
    ulimits:
      stack: 67108864
