services:
  hydrofabric:
    user: 1000
    build:
      context: ./ngen-workflow/
      dockerfile: Dockerfile
    volumes:
      - ./ngen-workflow:/ngen-workflow
    working_dir: /ngen-workflow
    ulimits:
      stack: 67108864
