stages:
  prepare:
    cmd: docker compose run --rm hydrofabric ./bash/prepare_reference_gpkg.sh ${vpuid} ${divides_file} ${flowpaths_file} ${hydrolocations_file} ${network_file}
    params:
    - vpuid
    - divides_file
    - flowpaths_file
    - hydrolocations_file
    - network_file
    deps:
    - ngen-workflow/bash/prepare_reference_gpkg.sh
    - ${divides_file}
    - ${flowpaths_file}
    - ${hydrolocations_file}
    - ${network_file}
    outs:
    - ngen-workflow/data/prepared
