---
title: "Add NOAH OWP Variables to the NGEN HydroFabric"
date: "2026-05-05"
params:
  nextgen_geopackage: "..."
  soil_data: "..."
  gw_params: "..."
---

```{r}
library(sf)
library(terra)
library(zonal)
library(dplyr)
library(powerjoin)
library(arrow)
library(glue)
```

```{r}
# define output file paths. These will be saved in the same
# directory as the input nextgen geopackage.
output_basepath <- dirname(params$nextgen_geopackage)
output_parquet <- file.path(output_basepath, "vaa_noahowp.parquet")
output_nextgen_geopackage <- file.path(output_basepath, "ngen_hydrofabric_vaa.gpkg")

```


```{r}
# read layers from the input nextgen geopackage
divides <- read_sf(params$nextgen_geopackage, "divides")

```


```{r}

nom_vars <- c("bexp", "dksat", "psisat", "smcmax", "smcwlt")
layers <- 1:4
files <- as.vector(glue("{params$soil_data}/{rep(nom_vars, each = 4)}_soil_layers_stag={rep(layers, times= length(nom_vars))}.tif"))

# read the input rasters into memory.
bexp_rasters <- rast(files[1:4])
dksat_rasters <- rast(files[5:8]) 
psisat_rasters <- rast(files[9:12]) 
smcmax_rasters <- rast(files[13:16]) 
smcwlt_rasters <- rast(files[17:20]) 

# Get Mode Beta parameter
modes = execute_zonal(bexp_rasters,
                    fun = "mode",
                    divides, ID = "divide_id", 
                    join = FALSE)
#%>% 
#        setNames(gsub("fun.", "mode.", names(.)))

# Get Geometric Mean of Saturated soil hydraulic conductivity, and matric potential
gm = execute_zonal(c(dksat_rasters, psisat_rasters), 
                   fun = geometric_mean,
                   divides, ID = "divide_id", 
                   join = FALSE)
gm <- gm %>%
     rename_with(~paste0("geom_mean.", .), -divide_id)

# Get Mean Saturated value of soil moisture and Wilting point soil moisture
m = execute_zonal(c(smcmax_rasters, smcwlt_rasters),
                    fun = "mean",
                    divides, ID = "divide_id", 
                    join = FALSE)
#%>% 
#    setNames(gsub("mean.", "", names(.)))

# Merge all tables into one
d1 <- power_full_join(list(modes, gm, m),  by = "divide_id")

```

## Groundwater Routing Parameters

```{r}

# what was once refered to as "conus_routelink" appears to be the
# nwm_gw_basins parquet file. This doesn't have a field called "hf_id",
# but I think this has been renamed "reference_id".
# TODO: Check with Mike that this assumption is correct
crosswalk <- read_sf(params$nextgen_geopackage, "network") |>
    select(reference_id, divide_id) |>
    collect()


# I modified the code here to use the "reference_id" field instead of "hf_id" for
# for the left portion of the join, and changed "hf_id" to "COMID" for the right 
# portion of the join.
# TODO: Check with Mike that this assumption is correct, and that the "reference_id"
# field in the network layer corresponds to the "COMID" field in the nwm_gw_basins table.
#
# Other changes I've made:
#   - removed the "gw_" prefix from setGenericw_Zmax, gw_Area_sqkm, gw_Coeff, and gw_Expon since
#     the nwm_gw_basins does not have these.
#   - added mutations to make sure that both ComID and reference_id are integers before the join
d2 <- open_dataset(params$gw_params) |>
    mutate(ComID = as.integer(ComID)) |>
    select(ComID , Coeff, Area_sqkm, Zmax, Expon) |>
    inner_join(mutate(crosswalk, reference_id = as.integer(reference_id)),
               by = c("ComID" = "reference_id")) |>
    group_by(divide_id) |>
    collect() |>
    summarize(
      mean.Coeff = round(weighted.mean(Coeff, w = Area_sqkm, na.rm = TRUE), 9),
      mean.Zmax  = round(weighted.mean(Zmax,  w = Area_sqkm, na.rm = TRUE), 9),
      mean.Expon = mode(floor(Expon))
    )

```

```{r}
# centroid of each divide
d3 <- st_centroid(divides) |>
  st_coordinates() |>
  data.frame() |>
  rename(centroid_x = X, centroid_y = Y) |>
  mutate(divide_id = divides$divide_id)
#  st_transform(4326) |>

## DEM attributes
## START HERE: !!!
#dem_vars <- c("elev", "slope", "aspect")
#
#r  <- rast(glue('{vsi}/250m_grids/usgs_250m_{dem_vars}.tif'))
#
#d4 <- execute_zonal(r[[1:2]], 
#                    div, ID = "divide_id", 
#                    join = FALSE) |>
#    setNames(c("divide_id", "elevation_mean", " slope"))
#
#d5 <- execute_zonal(r[[3]], 
#                     div, ID = "divide_id", fun = circular_mean, 
#                     join = FALSE) |>
#    setNames(c("divide_id", "aspect_c_mean"))
#
```



## Save the computed attributes

```{r}

# Save the attributes to a sidecar parquet file.
model_attributes <- power_full_join(list(d1, d2, d3), by = "divide_id")
#model_attributes <- power_full_join(list(d1, d2, d3, d4, d5), by = "divide_id")

write_parquet(model_attributes, output_parquet)


# Copy the input geopackage to a new file, then add the attributes
file.copy(params$nextgen_geopackage, output_nextgen_geopackage)

# add the model_attributes to the divide_attributes layer in the nextgen geopackage. 
gdf <- st_read(output_nextgen_geopackage, layer = "divide-attributes")
gdf_joined <- left_join(gdf, model_attributes, by = "divide_id")
st_write(gdf_joined, output_nextgen_geopackage, layer = "divide-attributes", delete_layer = TRUE)

```
