# only supporting vpuid 16 for demonstration and development
vpuids:
- id: "16"
  prefix: "16"
refactor:
  split_flines_meters: 10000
  collapse_flines_meters: 1000
  collapse_flines_main_meters: 1000
  simplify_tolerance_meters: 400
aggregate:
  ideal_size_sqkm: 5
  min_length_km: .5
  min_area_sqkm: 1
minimal_attributes:
  output_geopackage_name: ngen_hydrofabric_with_atts.gpkg
reconcile:
  output_geopackage_name: ngen_hydrofabric_reconciled.gpkg

