stages:
  export:
    cmd: >
      docker compose run --rm hydrofabric ./bash/export-gpkg-to-parquet.sh
      /ngen-workflow/output/${output_folder}/ngen_hydrofabric_reconciled.gpkg
      /ngen-workflow/output/${output_folder}/viewer/parquet
    deps:
      - ../../../ngen-workflow/bash/export-gpkg-to-parquet.sh
      - ../../../ngen-workflow/output/${output_folder}/ngen_hydrofabric_reconciled.gpkg
    outs:
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/divides.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/divide-attributes.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/flowpaths.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/flowpath-attributes.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/hydrolocations.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/nexus.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/network.parquet
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/network_graph.json
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/divides.geojsonseq
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/flowpaths.geojsonseq
  pmtiles:
    cmd: >
      mkdir -p ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference &&
      docker compose run --rm tippecanoe
      -o /ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/divides.pmtiles
      -l divides --drop-densest-as-needed --force
      /ngen-workflow/output/${output_folder}/viewer/parquet/divides.geojsonseq &&
      docker compose run --rm tippecanoe
      -o /ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/flowpaths.pmtiles
      -l flowpaths --drop-densest-as-needed --force
      /ngen-workflow/output/${output_folder}/viewer/parquet/flowpaths.geojsonseq
    deps:
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/divides.geojsonseq
      - ../../../ngen-workflow/output/${output_folder}/viewer/parquet/flowpaths.geojsonseq
    outs:
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/divides.pmtiles
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/flowpaths.pmtiles
  merged_pmtiles:
    cmd: >
      mkdir -p ../../../ngen-workflow/output/${output_folder}/viewer/map &&
      docker compose run --rm --entrypoint tile-join tippecanoe
      -o /ngen-workflow/output/${output_folder}/viewer/map/merged.pmtiles
      -pk
      --force
      /ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/divides.pmtiles
      /ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/flowpaths.pmtiles
    deps:
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/divides.pmtiles
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/flowpaths.pmtiles
    outs:
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/merged.pmtiles
  vpu_pmtiles:
    cmd: >
      mkdir -p ../../../ngen-workflow/output/${output_folder}/viewer/map ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference &&
      docker compose run --rm hydrofabric ./bash/build-vpu-pmtiles-input.sh /ngen-workflow/output/${output_folder}/viewer/map &&
      docker compose run --rm tippecanoe -o /ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/vpu.pmtiles -l vpu --force /ngen-workflow/output/${output_folder}/viewer/map/vpu.geojsonseq
    deps:
      - ../../../ngen-workflow/bash/build-vpu-pmtiles-input.sh
      - ../../../ngen-workflow/data/superconus/divides/
    outs:
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/vpu.pmtiles
  styles:
    cmd: >
      mkdir -p ../../../ngen-workflow/output/${output_folder}/viewer/map/styles &&
      sed -e 's|pmtiles://https://communityhydrofabric.s3.us-east-1.amazonaws.com/map/merged.pmtiles|pmtiles://../merged.pmtiles|'
      -e 's|pmtiles://https://communityhydrofabric.s3.us-east-1.amazonaws.com/map/vpu.pmtiles|pmtiles://../only_geometry/reference/vpu.pmtiles|'
      ../../../res_data/map/styles/dark-style.json
      > ../../../ngen-workflow/output/${output_folder}/viewer/map/styles/dark-style.json &&
      sed -e 's|pmtiles://https://communityhydrofabric.s3.us-east-1.amazonaws.com/map/merged.pmtiles|pmtiles://../merged.pmtiles|'
      -e 's|pmtiles://https://communityhydrofabric.s3.us-east-1.amazonaws.com/map/vpu.pmtiles|pmtiles://../only_geometry/reference/vpu.pmtiles|'
      ../../../res_data/map/styles/light-style.json
      > ../../../ngen-workflow/output/${output_folder}/viewer/map/styles/light-style.json
    deps:
      - ../../../res_data/map/styles/dark-style.json
      - ../../../res_data/map/styles/light-style.json
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/merged.pmtiles
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/only_geometry/reference/vpu.pmtiles
    outs:
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/styles/dark-style.json
      - ../../../ngen-workflow/output/${output_folder}/viewer/map/styles/light-style.json
